{
 "title": "New dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "app", "query": { "query": "label_values(container_name)" } }
  ]
 },
 "panels": [
  { "title": "Jvm app", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "response time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(http_server_requests_seconds_count{application=\"api-product\"}[1m])",
     "legendFormat": "{{application}}-{{status}}-{{uri}}"
    }
   ]
  },
  { "title": "go app", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "error on gateway",
   "type": "timeseries",
   "gridPos": { "h": 22, "w": 7, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(promhttp_metric_handler_requests_total{container_name=\"apigateway\"}[1m])",
     "legendFormat": "{{code}}-{{container_image}}"
    },
    {
     "expr": "increase(promhttp_metric_handler_requests_total{container_name=\"apicustomer\"}[1m])",
     "legendFormat": "{{code}}-{{container_image}}"
    }
   ]
  },
  {
   "title": "cpu",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 11 },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{container=\"$app\"}[1m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(http_response_duration_seconds_sum{container_name=\"$app\"}[1m])/increase(http_response_duration_seconds_count{container_name=\"$app\"}[1m])",
     "legendFormat": "{{container_image}}"
    }
   ]
  },
  {
   "title": "memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container=\"$app\"}) by (namespace, pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(container_memory_max_usage_bytes{container=\"$app\"}) by (namespace, pod)",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "RPM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(http_requests_total{container_name=\"$app\"}[1m])",
     "legendFormat": "{{container_image}}"
    }
   ]
  },
  {
   "title": "deployment scale",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 7, "y": 22 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{deployment=~\".*\"}",
     "legendFormat": "{{deployment}}"
    }
   ]
  }
 ]
}